name: "Auto Generate Next Release Tag"
description: "Automatically generate next release tag based on previous tag."
author: "CongThang1597"
branding:
  color: "red"
  icon: "tag"

inputs:
  GITHUB_TOKEN:
    description: "Github secrets token"
    required: true
  VERSION_BUILD:
    description: "Version build: major, minor, patch"
    required: false
  PREFIX:
    description: "Version prefix"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
