name: Auto Tag
on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    name: Auto tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate release tag
        uses: CongThang1597/generate-tag@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_BUILD: patch
          PREFIX: v

      - name: Push tag
        run: |
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: ''
          draft: false
          prerelease: false
