name: Auto Tag
on:
  push:
    branches:
      - master

jobs:
  auto-tag:
    name: Auto tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate release tag
        uses: CongThang1597/generate-tag@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_BUILD: patch
          PREFIX: v

      - name: Push tag
        run: |
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}
